---
title: "Linear Models"
author: "Jesus Luevano"
date: "2023-11-14"
output: html_document
---

#Linear Models

```{r}
library(tidyverse)
library(p8105.datasets)
```

## Load and clean the Airbnb data

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>%
  mutate(stars = review_scores_location /2) %>%
  select(price, stars, borough = neighbourhood_group, neighbourhood, room_type) %>%
  filter(borough != "Staten Island") 
```


Let's fit a model!!!

```{r}
#fit = lm(price ~ stars + borough, data = nyc_airbnb)

fit = 
  nyc_airbnb %>%
  lm(price ~ stars + borough, data = .) #label dataset not as first thing in lm but as "."; or _ if using |>
```

Let's look at the 'fit'

```{r}
fit
summary(fit)
#summary(fit)$coef
#coef(fit)
#fitted.values(fit)
```

Tidy up the output instead

```{r}
fit %>%
  broom::glance()
```

tidy up the coefficients

```{r}
fit %>%
  broom::tidy() %>%
  mutate(term = str_replace(term, "^borough", "Borough: ")) %>%
  select(term, estimate, p.value) %>%
  knitr::kable(digits = 3)

```


## Fit another model

```{r}
fit =
  nyc_airbnb %>%
  mutate(
    borough = fct_infreq(borough),
    room_type = fct_infreq(room_type)
  ) %>%
  lm(price ~ stars + borough + room_type, data = .)

fit %>%
  broom::tidy()
```


## Quick look at diagnostics

```{r}
nyc_airbnb %>%
  modelr::add_residuals(fit) %>%
  ggplot(aes(x = resid)) + 
  geom_density() + 
  xlim(-100, 500) #shows residuals not right at zero, and smaller peaks likely that prices tend to be put up at round numbers

nyc_airbnb %>%
  modelr::add_residuals(fit) %>%
  ggplot(aes(x = borough, y = resid)) +
  geom_violin()

nyc_airbnb %>%
  modelr::add_residuals(fit) %>%
  ggplot(aes(x = stars, y = resid)) +
  geom_point()

```

## Hypothesis test for categorical predictor

Fit a 'null' and 'alternative' model

```{r}
fit_null = lm(price ~ stars + borough, data = nyc_airbnb)
fit_alternative = lm(price ~ stars + borough + room_type, data = nyc_airbnb)

anova(fit_null, fit_alternative) %>%
  broom::tidy()
```


## Borough-level differences

```{r}
fit = 
  nyc_airbnb %>%
  lm(price ~ stars * borough + room_type * borough, data = .)

fit %>%
  broom::tidy()
```


```{r}
airbnb_lm = function(df){
  lm(price ~ stars + room_type, data = df)
}

nyc_airbnb %>%
  nest(df = -borough) %>% #nest everything BUT borough 
  mutate(
    models = map(df, airbnb_lm),
    results = map(models, broom::tidy)
  ) %>%
  select(borough, results) %>%
  unnest(results) %>%
  select(borough, term, estimate) %>%
  pivot_wider(
    names_from = term,
    values_from = estimate
  ) %>%
  knitr::kable(digits = 2)
```

same thing but a bit different, anonymous function

```{r}
nyc_airbnb %>%
  nest(df = -borough) %>% #nest everything BUT borough 
  mutate(
    models = map(df, \(df) lm(price ~ stars + room_type, data = df)), #internal function instead of in global environemnt, called anonymous function
    results = map(models, broom::tidy)
  ) %>%
  select(borough, results) %>%
  unnest(results) %>%
  select(borough, term, estimate) %>%
  pivot_wider(
    names_from = term,
    values_from = estimate
  ) %>%
  knitr::kable(digits = 2)
```

